// Embedded catalog of disposable / temporary / throwaway email domains.
// These are domains run by services like Mailinator, 10MinuteMail, Guerrilla
// Mail, Temp-Mail, etc. An address on one of them is almost never a real,
// reachable, long-lived inbox — which is exactly the signal list-cleaning and
// signup-fraud teams pay to detect. The list is embedded (no network fetch) so
// the check is instant and works in a serverless cold start.
//
// Curated from the widely-used public disposable-domain blocklists
// (disposable-email-domains, mailchecker, etc.), trimmed to the high-signal
// entries plus their common wildcards handled in code below.

export const DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set([
  "0-mail.com", "0clickemail.com", "0wnd.net", "0wnd.org", "10minutemail.com",
  "10minutemail.net", "10minutemail.org", "10minutemail.co.uk", "10minemail.com",
  "20minutemail.com", "20email.eu", "30minutemail.com", "33mail.com",
  "60minutemail.com", "anonbox.net", "anonymbox.com", "armyspy.com",
  "bccto.me", "binkmail.com", "bobmail.info", "bofthew.com", "boun.cr",
  "bouncr.com", "boximail.com", "brefmail.com", "bsnow.net", "bspamfree.org",
  "bugmenot.com", "bumpymail.com", "burnermail.io", "byom.de", "cachedot.net",
  "chacuo.net", "chammy.info", "cheatemail.com", "cool.fr.nf", "courriel.fr.nf",
  "cpmail.life", "crapmail.org", "cust.in", "dacoolest.com", "dandikmail.com",
  "dayrep.com", "deadaddress.com", "deadspam.com", "despam.it", "devnullmail.com",
  "dingbone.com", "discard.email", "discardmail.com", "discardmail.de",
  "disposable.com", "disposableinbox.com", "dispose.it", "dispostable.com",
  "dodgeit.com", "dodgit.com", "donemail.ru", "dontreg.com", "dontsendmespam.de",
  "drdrb.com", "drdrb.net", "dump-email.info", "dumpandjunk.com", "dumpmail.de",
  "dumpyemail.com", "e4ward.com", "easytrashmail.com", "einrot.com",
  "email-fake.com", "emailgo.de", "emailias.com", "emailmiser.com",
  "emailondeck.com", "emailsensei.com", "emailtemporanea.com", "emailtemporanea.net",
  "emailtemporario.com.br", "emailthe.net", "emailtmp.com", "emailwarden.com",
  "emailx.at.hm", "emailxfer.com", "emeil.in", "emeil.ir", "emz.net",
  "evopo.com", "explodemail.com", "fakeinbox.com", "fakemail.fr",
  "fakemailgenerator.com", "fastmazda.com", "fightallspam.com", "filzmail.com",
  "fizmail.com", "fleckens.hu", "fr33mail.info", "frapmail.com", "front14.org",
  "fux0ringduh.com", "garliclife.com", "gehensiemirnichtaufdensack.de",
  "get1mail.com", "get2mail.fr", "getairmail.com", "getnada.com", "ghosttexter.de",
  "girlsundertheinfluence.com", "gishpuppy.com", "gmial.com", "goemailgo.com",
  "great-host.in", "greensloth.com", "grr.la", "guerillamail.biz",
  "guerillamail.com", "guerillamail.de", "guerillamail.net", "guerillamail.org",
  "guerrillamail.biz", "guerrillamail.com", "guerrillamail.de", "guerrillamail.info",
  "guerrillamail.net", "guerrillamail.org", "guerrillamailblock.com",
  "h.mintemail.com", "hatespam.org", "hidemail.de", "hidzz.com", "hmamail.com",
  "hochsitze.com", "hotpop.com", "hulapla.de", "ieatspam.eu", "ieatspam.info",
  "ihateyoualot.info", "iheartspam.org", "imails.info", "inboxalias.com",
  "inboxbear.com", "incognitomail.com", "incognitomail.net", "incognitomail.org",
  "insorg-mail.info", "instant-mail.de", "ipoo.org", "irish2me.com",
  "iwi.net", "jetable.com", "jetable.fr.nf", "jetable.net", "jetable.org",
  "jnxjn.com", "junk1e.com", "kasmail.com", "kaspop.com", "killmail.com",
  "killmail.net", "klassmaster.com", "klzlk.com", "koszmail.pl", "kurzepost.de",
  "lawlita.com", "letthemeatspam.com", "lhsdv.com", "lifebyfood.com",
  "link2mail.net", "litedrop.com", "lol.ovpn.to", "lookugly.com", "lopl.co.cc",
  "lortemail.dk", "lr78.com", "lroid.com", "luckymail.org", "m21.cc",
  "mail-filter.com", "mail-temporaire.fr", "mail.by", "mail.mezimages.net",
  "mail2rss.org", "mail333.com", "mailbidon.com", "mailbiz.biz", "mailblocks.com",
  "mailbucket.org", "mailcat.biz", "mailcatch.com", "mailde.de", "mailde.info",
  "maildrop.cc", "maileater.com", "mailexpire.com", "mailfa.tk", "mailforspam.com",
  "mailfreeonline.com", "mailguard.me", "mailimate.com", "mailin8r.com",
  "mailinater.com", "mailinator.com", "mailinator.net", "mailinator.org",
  "mailinator2.com", "mailincubator.com", "mailismagic.com", "mailme.lv",
  "mailme24.com", "mailmetrash.com", "mailmoat.com", "mailnator.com",
  "mailnesia.com", "mailnull.com", "mailorg.org", "mailpick.biz", "mailrock.biz",
  "mailscrap.com", "mailshell.com", "mailsiphon.com", "mailslite.com",
  "mailtemp.info", "mailtothis.com", "mailtrash.net", "mailtv.net", "mailzilla.com",
  "mailzilla.org", "makemetheking.com", "manybrain.com", "mbx.cc", "mega.zik.dj",
  "meinspamschutz.de", "meltmail.com", "messagebeamer.de", "mezimages.net",
  "mintemail.com", "moakt.com", "mobi.web.id", "moburl.com", "mohmal.com",
  "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf", "msa.minsmail.com",
  "mt2009.com", "mt2014.com", "mt2015.com", "mvrht.com", "mx0.wwwnew.eu",
  "mycleaninbox.net", "mymail-in.net", "mypacks.net", "mypartyclip.de",
  "myphantomemail.com", "mysamp.de", "mytrashmail.com", "nabuma.com",
  "neomailbox.com", "nepwk.com", "nervmich.net", "nervtmich.net", "netmails.com",
  "netmails.net", "netzidiot.de", "neverbox.com", "no-spam.ws", "nobulk.com",
  "noclickemail.com", "nogmailspam.info", "nomail.xl.cx", "nomail2me.com",
  "nomorespamemails.com", "nospam.ze.tc", "nospam4.us", "nospamfor.us",
  "nospammail.net", "notmailinator.com", "nowhere.org", "nowmymail.com",
  "nurfuerspam.de", "nwldx.com", "objectmail.com", "obobbo.com", "odnorazovoe.ru",
  "oneoffemail.com", "onewaymail.com", "onlatedotcom.info", "online.ms",
  "oopi.org", "ordinaryamerican.net", "otherinbox.com", "ourklips.com",
  "outlawspam.com", "ovpn.to", "owlpic.com", "pancakemail.com", "pcusers.otherinbox.com",
  "pjjkp.com", "plexolan.de", "poczta.onet.pl", "politikerclub.de", "poofy.org",
  "pookmail.com", "privacy.net", "privatdemail.net", "proxymail.eu", "prtnx.com",
  "putthisinyourspamdatabase.com", "putzlowitsch.de", "qq.com", "quickinbox.com",
  "rcpt.at", "reallymymail.com", "realtyalerts.ca", "recode.me", "recursor.net",
  "reliable-mail.com", "rhyta.com", "rmqkr.net", "royal.net", "rppkn.com",
  "rtrtr.com", "s0ny.net", "safe-mail.net", "safersignup.de", "safetymail.info",
  "safetypost.de", "saynotospams.com", "schafmail.de", "schrott-email.de",
  "secretemail.de", "secure-mail.biz", "selfdestructingmail.com", "sendspamhere.com",
  "sharklasers.com", "shieldemail.com", "shiftmail.com", "shitmail.me", "shitware.nl",
  "shmeriously.com", "shortmail.net", "sibmail.com", "skeefmail.com", "slapsfromlastnight.com",
  "slaskpost.se", "smashmail.de", "smellfear.com", "snakemail.com", "sneakemail.com",
  "snkmail.com", "sofimail.com", "sofort-mail.de", "sogetthis.com", "soodonims.com",
  "spam.la", "spam.su", "spam4.me", "spamavert.com", "spambob.com", "spambob.net",
  "spambob.org", "spambog.com", "spambog.de", "spambog.ru", "spambox.us",
  "spamcannon.com", "spamcannon.net", "spamcero.com", "spamcon.org", "spamcorptastic.com",
  "spamcowboy.com", "spamcowboy.net", "spamcowboy.org", "spamday.com", "spamex.com",
  "spamfree24.com", "spamfree24.de", "spamfree24.eu", "spamfree24.info", "spamfree24.net",
  "spamfree24.org", "spamgoes.in", "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
  "spamherelots.com", "spamhereplease.com", "spamhole.com", "spamify.com",
  "spaminator.de", "spamkill.info", "spaml.com", "spaml.de", "spammotel.com",
  "spamobox.com", "spamslicer.com", "spamspot.com", "spamthis.co.uk", "spamtroll.net",
  "speed.1s.fr", "spoofmail.de", "stuffmail.de", "supergreatmail.com", "supermailer.jp",
  "suremail.info", "talkinator.com", "teewars.org", "teleworm.com", "teleworm.us",
  "temp-mail.org", "temp-mail.ru", "tempail.com", "tempalias.com", "tempe-mail.com",
  "tempemail.biz", "tempemail.com", "tempemail.net", "tempinbox.co.uk", "tempinbox.com",
  "tempmail.eu", "tempmail.it", "tempmail2.com", "tempmaildemo.com", "tempmailer.com",
  "tempmailer.de", "tempomail.fr", "temporarily.de", "temporarioemail.com.br",
  "temporaryemail.net", "temporaryforwarding.com", "temporaryinbox.com",
  "temporarymailaddress.com", "tempthe.net", "thanksnospam.info", "thankyou2010.com",
  "thc.st", "thelimestones.com", "thisisnotmyrealemail.com", "thismail.net",
  "throwawayemailaddress.com", "tilien.com", "tittbit.in", "tmail.ws", "tmailinator.com",
  "toiea.com", "toomail.biz", "topranklist.de", "tradermail.info", "trash-mail.at",
  "trash-mail.com", "trash-mail.de", "trash2009.com", "trashdevil.com", "trashemail.de",
  "trashmail.at", "trashmail.com", "trashmail.de", "trashmail.me", "trashmail.net",
  "trashmail.org", "trashmail.ws", "trashmailer.com", "trashymail.com", "trashymail.net",
  "trillianpro.com", "twinmail.de", "tyldd.com", "uggsrock.com", "upliftnow.com",
  "uplipht.com", "uroid.com", "us.af", "venompen.com", "veryrealemail.com",
  "viditag.com", "viralplays.com", "vpn.st", "vsimcard.com", "vubby.com",
  "wasteland.rfc822.org", "webemail.me", "weg-werf-email.de", "wegwerf-emails.de",
  "wegwerfadresse.de", "wegwerfemail.com", "wegwerfemail.de", "wegwerfmail.de",
  "wegwerfmail.info", "wegwerfmail.net", "wegwerfmail.org", "wetrainbayarea.com",
  "wh4f.org", "whyspam.me", "willhackforfood.biz", "willselfdestruct.com",
  "winemaven.info", "wronghead.com", "wuzup.net", "wuzupmail.net", "www.e4ward.com",
  "www.mailinator.com", "wwwnew.eu", "x.ip6.li", "xagloo.com", "xemaps.com",
  "xents.com", "xmaily.com", "xoxy.net", "yapped.net", "yeah.net", "yep.it",
  "yogamaven.com", "yopmail.com", "yopmail.fr", "yopmail.net", "yourdomain.com",
  "yuurok.com", "z1p.biz", "za.com", "zehnminutenmail.de", "zippymail.info",
  "zoemail.net", "zoemail.org", "zomg.info",
  // 2023-2026 additions seen in fraud feeds
  "1secmail.com", "1secmail.net", "1secmail.org", "esiix.com", "wwjmp.com",
  "xojxe.com", "yoggm.com", "dropmail.me", "10mail.org", "33m.co", "fakemail.net",
  "luxusmail.org", "guerrillamail.click", "spam4.me", "burpcollaborator.net",
  "mailpoof.com", "tempr.email", "discard.email", "mailto.plus", "fexpost.com",
  "fexbox.org", "mailbox.in.ua", "rover.info", "chitthi.in", "fextemp.com",
  "any.pink", "merepost.com", "cevipsa.com", "vafyxh.com", "etlgr.com",
  "mailcup.online", "inboxkitten.com", "tmpmail.org", "tmpmail.net", "tmpbox.net",
  "moakt.cc", "moakt.ws", "tmpeml.com", "tmpmailtor.com", "tempmailo.com",
]);

// Some disposable providers spin up many random subdomains under a single
// parent. Match the registrable parent too.
const DISPOSABLE_SUFFIXES: readonly string[] = [
  ".mailinator.com", ".guerrillamail.com", ".yopmail.com", ".trashmail.com",
  ".1secmail.com", ".1secmail.net", ".1secmail.org", ".dropmail.me",
  ".moakt.cc", ".temp-mail.org", ".33mail.com",
];

export function isDisposableDomain(domain: string): boolean {
  const d = domain.toLowerCase();
  if (DISPOSABLE_DOMAINS.has(d)) return true;
  for (const suf of DISPOSABLE_SUFFIXES) {
    if (d.endsWith(suf)) return true;
  }
  return false;
}
